import { Language } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', label: 'English', icon: 'EN', color: 'bg-blue-400' },
  { code: 'hi', name: 'Hindi', label: 'हिन्दी', icon: 'हिं', color: 'bg-orange-400' },
  { code: 'gu', name: 'Gujarati', label: 'ગુજરાતી', icon: 'ગુ', color: 'bg-pink-500' },
  { code: 'mr', name: 'Marathi', label: 'मराठी', icon: 'म', color: 'bg-purple-400' },
  { code: 'bn', name: 'Bengali', label: 'বাংলা', icon: 'বা', color: 'bg-green-400' },
  { code: 'ta', name: 'Tamil', label: 'தமிழ்', icon: 'த', color: 'bg-red-400' },
  { code: 'te', name: 'Telugu', label: 'తెలుగు', icon: 'తె', color: 'bg-yellow-500' },
  { code: 'kn', name: 'Kannada', label: 'ಕನ್ನಡ', icon: 'ಕ', color: 'bg-emerald-500' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appTitle: "Math Safari",
    appSubtitle: "Join the Expedition!",
    learnBtn: "Learn Secrets",
    startBtn: "Start Adventure",
    fieldGuide: "Field Guide",
    chooseLevel: "Choose Level",
    back: "Back",
    next: "Next",
    finish: "Finish",
    skip: "Skip",
    go: "GO",
    del: "DEL",
    oops: "Oops! Try again.",
    awesome: "Awesome!",
    nextChallenge: "Next Challenge",
    nextPart: "Next Part",
    gotIt: "Got it, Next Part",
    finishStory: "Finish Story",
    guideSays: "Guide says:",
    easyAdd: "Easy Add!",
    findHidden: "Find the hidden numbers to reveal the keypad!",
    breakNum: "Break",
    perfect: "Perfect!",
    findTen: "Find the Ten",
    letsLearn: "Let's Learn!",
    correctIs: "The correct answer is",
    writingStory: "Writing a new story...",
    congrats: "CONGRATULATIONS!",
    points: "You reached",
    l1_name: "Baby Steps", l1_desc: "Adding Ones (1-9)",
    l2_name: "Ten Tribe", l2_desc: "Adding Tens (10, 20...)",
    l3_name: "The Breaker", l3_desc: "Break & Add (Interactive)",
    l4_name: "Tiny Takeaway", l4_desc: "Subtracting Ones",
    l5_name: "Big Drop", l5_desc: "Subtracting Tens",
    l6_name: "Jungle Master", l6_desc: "Mixed Challenge",
    l7_name: "Story Safari", l7_desc: "Read, Remember & Solve!",
    step: "Step",
    of: "of",
    foundation: "Foundation",
    smart: "Smart",
    breakTitle: "Break It Down",
    breakDesc: "Split numbers into Tens and Ones!",
    friendlyTitle: "Friendly Numbers",
    friendlyDesc: "Turn messy numbers into nice numbers ending in Zero.",
    selectLang: "Select Language",
    hiGuide: "Hi! I am Leo. Pick your language!"
  },
  gu: {
    appTitle: "ગણિત સફારી",
    appSubtitle: "અભિયાનમાં જોડાઓ!",
    learnBtn: "રહસ્યો શીખો",
    startBtn: "સાહસ શરૂ કરો",
    fieldGuide: "ફીલ્ડ ગાઈડ",
    chooseLevel: "સ્તર પસંદ કરો",
    back: "પાછા",
    next: "આગળ",
    finish: "સમાપ્ત",
    skip: "છોડો",
    go: "જાઓ",
    del: "ભૂંસો",
    oops: "અરે! ફરી પ્રયાસ કરો.",
    awesome: "ખૂબ સરસ!",
    nextChallenge: "આગળનો પડકાર",
    nextPart: "આગળનો ભાગ",
    gotIt: "સમજાઈ ગયું",
    finishStory: "વાર્તા પૂરી",
    guideSays: "ગાઈડ કહે છે:",
    easyAdd: "સરળ સરવાળો!",
    findHidden: "કીપેડ જોવા માટે છુપાયેલા નંબરો શોધો!",
    breakNum: "તોડો",
    perfect: "ઉત્તમ!",
    findTen: "દસ શોધો",
    letsLearn: "ચાલો શીખીએ!",
    correctIs: "સાચો જવાબ છે",
    writingStory: "નવી વાર્તા લખાઈ રહી છે...",
    congrats: "અભિનંદન!",
    points: "તમે પહોંચ્યા",
    l1_name: "નાના ડગલાં", l1_desc: "એક અંકનો સરવાળો (1-9)",
    l2_name: "દસની ટોળકી", l2_desc: "દસ ઉમેરવા (10, 20...)",
    l3_name: "નંબર બ્રેકર", l3_desc: "તોડો અને ઉમેરો",
    l4_name: "નાની બાદબાકી", l4_desc: "એક અંકની બાદબાકી",
    l5_name: "મોટી બાદબાકી", l5_desc: "દસની બાદબાકી",
    l6_name: "જંગલ માસ્ટર", l6_desc: "મિશ્ર પડકાર",
    l7_name: "વાર્તા સફારી", l7_desc: "વાંચો, યાદ રાખો અને ઉકેલો!",
    step: "પગલું",
    of: "માંથી",
    foundation: "પાયો",
    smart: "સ્માર્ટ",
    breakTitle: "તોડીને જુઓ",
    breakDesc: "સંખ્યાઓને દસ અને એકમમાં વહેંચો!",
    friendlyTitle: "મિત્ર સંખ્યાઓ",
    friendlyDesc: "અઘરા નંબરોને શૂન્યવાળા સરળ નંબરોમાં ફેરવો.",
    selectLang: "ભાષા પસંદ કરો",
    hiGuide: "નમસ્તે! હું લિયો છું. તમારી ભાષા પસંદ કરો!"
  },
  hi: {
    appTitle: "गणित सफारी",
    appSubtitle: "अभियान में शामिल हों!",
    learnBtn: "रहस्य सीखें",
    startBtn: "साहसिक कार्य शुरू करें",
    fieldGuide: "फील्ड गाइड",
    chooseLevel: "स्तर चुनें",
    back: "पीछे",
    next: "अगला",
    finish: "समाप्त",
    skip: "छोड़ें",
    go: "जाएं",
    del: "हटाएं",
    oops: "ओह! पुनः प्रयास करें।",
    awesome: "बहुत बढ़िया!",
    nextChallenge: "अगली चुनौती",
    nextPart: "अगला भाग",
    gotIt: "समझ गया, अगला भाग",
    finishStory: "कहानी समाप्त",
    guideSays: "गाइड कहते हैं:",
    easyAdd: "आसान जोड़!",
    findHidden: "कीपैड देखने के लिए छिपे हुए नंबर ढूंढें!",
    breakNum: "तोड़ें",
    perfect: "बेहतरीन!",
    findTen: "दहाई ढूंढें",
    letsLearn: "चलो सीखते हैं!",
    correctIs: "सही उत्तर है",
    writingStory: "नई कहानी लिख रहे हैं...",
    congrats: "बधाई हो!",
    points: "आपने प्राप्त किए",
    l1_name: "नन्हे कदम", l1_desc: "इकाई जोड़ना (1-9)",
    l2_name: "दहाई कबीला", l2_desc: "दहाई जोड़ना (10, 20...)",
    l3_name: "नंबर ब्रेकर", l3_desc: "तोड़ें और जोड़ें (इंटरैक्टिव)",
    l4_name: "छोटा घटाव", l4_desc: "इकाई घटाना",
    l5_name: "बड़ी गिरावट", l5_desc: "दहाई घटाना",
    l6_name: "जंगल मास्टर", l6_desc: "मिश्रित चुनौती",
    l7_name: "कहानी सफारी", l7_desc: "पढ़ें, याद रखें और हल करें!",
    step: "कदम",
    of: "में से",
    foundation: "बुनियाद",
    smart: "स्मार्ट",
    breakTitle: "इसे तोड़ें",
    breakDesc: "संख्याओं को दहाई और इकाई में विभाजित करें!",
    friendlyTitle: "दोस्ताना नंबर",
    friendlyDesc: "मुश्किल नंबरों को शून्य वाले आसान नंबरों में बदलें।",
    selectLang: "भाषा चुनें",
    hiGuide: "नमस्ते! मैं लियो हूँ। अपनी भाषा चुनें!"
  },
  mr: {
    appTitle: "गणित सफारी",
    appSubtitle: "मोहिमेत सामील व्हा!",
    learnBtn: "गुपिते शिका",
    startBtn: "साहस सुरू करा",
    fieldGuide: "फील्ड गाइड",
    chooseLevel: "स्तर निवडा",
    back: "मागे",
    next: "पुढे",
    finish: "समाप्त",
    skip: "वगळा",
    go: "जा",
    del: "काढा",
    oops: "अरेरे! पुन्हा प्रयत्न करा.",
    awesome: "मस्त!",
    nextChallenge: "पुढील आव्हान",
    nextPart: "पुढील भाग",
    gotIt: "समजले, पुढील भाग",
    finishStory: "गोष्ट पूर्ण",
    guideSays: "गाईड म्हणतात:",
    easyAdd: "सोपी बेरीज!",
    findHidden: "कीपॅड पाहण्यासाठी लपलेले अंक शोधा!",
    breakNum: "फोडा",
    perfect: "उत्तम!",
    findTen: "दशक शोधा",
    letsLearn: " चला शिकूया!",
    correctIs: "अचूक उत्तर आहे",
    writingStory: "नवीन गोष्ट लिहीत आहे...",
    congrats: "अभिनंदन!",
    points: "तुम्ही मिळवले",
    l1_name: "छोटे पाऊल", l1_desc: "एकक बेरीज (1-9)",
    l2_name: "दशक टोळी", l2_desc: "दशक बेरीज (10, 20...)",
    l3_name: "नंबर ब्रेकर", l3_desc: "फोडा आणि जोडा",
    l4_name: "छोटा वजाबाकी", l4_desc: "एकक वजाबाकी",
    l5_name: "मोठा वजाबाकी", l5_desc: "दशक वजाबाकी",
    l6_name: "जंगल मास्टर", l6_desc: "मिश्रित आव्हान",
    l7_name: "गोष्ट सफारी", l7_desc: "वाचा, लक्षात ठेवा आणि सोडवा!",
    step: "पाऊल",
    of: "पैकी",
    foundation: "पाया",
    smart: "स्मार्ट",
    breakTitle: "फोडून शिका",
    breakDesc: "संख्या दशक आणि एकक मध्ये विभागणी करा!",
    friendlyTitle: "मैत्रीपूर्ण संख्या",
    friendlyDesc: "कठीण संख्यांना शून्य असलेल्या सोप्या संख्यांमध्ये बदला.",
    selectLang: "भाषा निवडा",
    hiGuide: "नमस्कार! मी लिओ आहे. तुमची भाषा निवडा!"
  },
  bn: {
    appTitle: "গণিত সাফারি",
    appSubtitle: "অভিযানে যোগ দিন!",
    learnBtn: "গোপন সূত্র শিখুন",
    startBtn: "অ্যাডভেঞ্চার শুরু করুন",
    fieldGuide: "ফিল্ড গাইড",
    chooseLevel: "লেভেল বাছুন",
    back: "ফিরে যান",
    next: "পরবর্তী",
    finish: "সমাপ্ত",
    skip: "এড়িয়ে যান",
    go: "যাও",
    del: "মুছুন",
    oops: "ওহো! আবার চেষ্টা করুন।",
    awesome: "দারুণ!",
    nextChallenge: "পরবর্তী চ্যালেঞ্জ",
    nextPart: "পরবর্তী অংশ",
    gotIt: "বুঝেছি, পরবর্তী অংশ",
    finishStory: "গল্প শেষ করুন",
    guideSays: "গাইড বলছে:",
    easyAdd: "সহজ যোগ!",
    findHidden: "কীবোর্ড দেখতে লুকানো সংখ্যাগুলি খুঁজুন!",
    breakNum: "ভাঙুন",
    perfect: "নিখুঁত!",
    findTen: "দশ খুঁজুন",
    letsLearn: "আসুন শিখি!",
    correctIs: "সঠিক উত্তর হলো",
    writingStory: "নতুন গল্প লেখা হচ্ছে...",
    congrats: "অভিনন্দন!",
    points: "আপনি পৌঁছেছেন",
    l1_name: "শিশুর পদক্ষেপ", l1_desc: "একক সংখ্যা যোগ (১-৯)",
    l2_name: "দশের দল", l2_desc: "দশ যোগ করা (১০, ২০...)",
    l3_name: "ব্রেকার", l3_desc: "ভাঙুন এবং যোগ করুন",
    l4_name: "ছোট বিয়োগ", l4_desc: "একক সংখ্যা বিয়োগ",
    l5_name: "বড় পতন", l5_desc: "দশ বিয়োগ",
    l6_name: "জঙ্গল মাস্টার", l6_desc: "মিশ্র চ্যালেঞ্জ",
    l7_name: "গল্প সাফারি", l7_desc: "পড়ুন, মনে রাখুন এবং সমাধান করুন!",
    step: "ধাপ",
    of: "এর",
    foundation: "ভিত্তি",
    smart: "স্মার্ট",
    breakTitle: "এটি ভেঙে ফেলুন",
    breakDesc: "সংখ্যাগুলিকে দশ এবং এককে ভাগ করুন!",
    friendlyTitle: "বন্ধুত্বপূর্ণ সংখ্যা",
    friendlyDesc: "কঠিন সংখ্যাগুলিকে শূন্য দিয়ে শেষ হওয়া সহজ সংখ্যায় পরিণত করুন।",
    selectLang: "ভাষা নির্বাচন করুন",
    hiGuide: "নমস্কার! আমি লিও। আপনার ভাষা বাছুন!"
  },
  ta: {
    appTitle: "கணித சபாரி",
    appSubtitle: "பயணத்தில் சேருங்கள்!",
    learnBtn: "ரகசியங்களைக் கற்றுக்கொள்",
    startBtn: "சாகசத்தைத் தொடங்கு",
    fieldGuide: "வழிகாட்டி",
    chooseLevel: "நிலையைத் தேர்ந்தெடு",
    back: "பின்னால்",
    next: "அடுத்து",
    finish: "முடி",
    skip: "தவிர்",
    go: "செல்",
    del: "நீக்கு",
    oops: "அய்யோ! மீண்டும் முயற்சிக்கவும்.",
    awesome: "அருமை!",
    nextChallenge: "அடுத்த சவால்",
    nextPart: "அடுத்த பகுதி",
    gotIt: "புரிந்தது, அடுத்த பகுதி",
    finishStory: "கதையை முடி",
    guideSays: "வழிகாட்டி கூறுகிறார்:",
    easyAdd: "எளிதான கூட்டல்!",
    findHidden: "விசைப்பலகையைக் காண மறைந்திருக்கும் எண்களைக் கண்டறியவும்!",
    breakNum: "பிரி",
    perfect: "மிகச் சிறப்பு!",
    findTen: "பத்தை கண்டுபிடி",
    letsLearn: "கற்றுக்கொள்ளலாம் வாருங்கள்!",
    correctIs: "சரியான பதில்",
    writingStory: "புதிய கதை எழுதுகிறேன்...",
    congrats: "வாழ்த்துக்கள்!",
    points: "நீங்கள் அடைந்த புள்ளிகள்",
    l1_name: "சிறு படிகள்", l1_desc: "ஒன்றுகளைக் கூட்டுதல் (1-9)",
    l2_name: "பத்து குழு", l2_desc: "பத்துக்களைக் கூட்டுதல் (10, 20...)",
    l3_name: "எண் பிரிப்பவர்", l3_desc: "பிரித்து கூட்டவும்",
    l4_name: "சிறு கழித்தல்", l4_desc: "ஒன்றுகளைக் கழித்தல்",
    l5_name: "பெரிய கழித்தல்", l5_desc: "பத்துக்களைக் கழித்தல்",
    l6_name: "காட்டு மன்னன்", l6_desc: "கலவையான சவால்",
    l7_name: "கதை சபாரி", l7_desc: "படியுங்கள், நினைவில் கொள்ளுங்கள், தீர்வு காணுங்கள்!",
    step: "படி",
    of: "இல்",
    foundation: "அடிப்படை",
    smart: "சாமர்த்தியம்",
    breakTitle: "பிரித்துப்பார்",
    breakDesc: "எண்களை பத்துக்களாகவும் ஒன்றுகளாகவும் பிரிக்கவும்!",
    friendlyTitle: "நட்பு எண்கள்",
    friendlyDesc: "கடினமான எண்களை பூஜ்ஜியத்தில் முடியும் எண்களாக மாற்றவும்.",
    selectLang: "மொழியைத் தேர்ந்தெடு",
    hiGuide: "வணக்கம்! நான் லியோ. உங்கள் மொழியைத் தேர்வு செய்யவும்!"
  },
  te: {
    appTitle: "మ్యాథ్ సఫారీ",
    appSubtitle: "యాత్రలో చేరండి!",
    learnBtn: "రహస్యాలు నేర్చుకో",
    startBtn: "సాహసం ప్రారంభించు",
    fieldGuide: "ఫీల్డ్ గైడ్",
    chooseLevel: "స్థాయిని ఎంచుకో",
    back: "వెనుకకు",
    next: "తరువాత",
    finish: "ముగించు",
    skip: "వదిలేయండి",
    go: "వెళ్ళు",
    del: "తొలగించు",
    oops: "అయ్యో! మళ్ళీ ప్రయత్నించు.",
    awesome: "అద్భుతం!",
    nextChallenge: "తదుపరి సవాలు",
    nextPart: "తదుపరి భాగం",
    gotIt: "అర్థమైంది, నెక్స్ట్ పార్ట్",
    finishStory: "కథ ముగించు",
    guideSays: "గైడ్ చెబుతున్నారు:",
    easyAdd: "సులభమైన కూడిక!",
    findHidden: "కీప్యాడ్ చూడటానికి దాగి ఉన్న సంఖ్యలను కనుగొనండి!",
    breakNum: "విడగొట్టు",
    perfect: "చాలా బాగుంది!",
    findTen: "పదిని కనుగొను",
    letsLearn: "నేర్చుకుందాం రండి!",
    correctIs: "సరైన సమాధానం",
    writingStory: "కొత్త కథ రాస్తున్నాను...",
    congrats: "అభినందనలు!",
    points: "మీ స్కోరు",
    l1_name: "చిన్న అడుగులు", l1_desc: "ఒకట్లను కూడటం (1-9)",
    l2_name: "పదుల గుంపు", l2_desc: "పదులను కూడటం (10, 20...)",
    l3_name: "నంబర్ బ్రేకర్", l3_desc: "విడగొట్టి కూడండి",
    l4_name: "చిన్న తీసివేత", l4_desc: "ఒకట్లను తీసివేయడం",
    l5_name: "పెద్ద తీసివేత", l5_desc: "పదులను తీసివేయడం",
    l6_name: "జంగిల్ మాస్టర్", l6_desc: "మిశ్రమ సవాలు",
    l7_name: "స్టోరీ సఫారీ", l7_desc: "చదవండి, గుర్తుంచుకోండి, సాధించండి!",
    step: "అడుగు",
    of: "లో",
    foundation: "పునాది",
    smart: "తెలివైన",
    breakTitle: "విడగొట్టండి",
    breakDesc: "సంఖ్యలను పదులు మరియు ఒకట్లుగా విడగొట్టండి!",
    friendlyTitle: "స్నేహపూర్వక సంఖ్యలు",
    friendlyDesc: "కష్టమైన సంఖ్యలను సున్నా తో ముగిసే సులభమైన సంఖ్యలుగా మార్చండి.",
    selectLang: "భాషను ఎంచుకోండి",
    hiGuide: "నమస్కారం! నేను లియో. మీ భాషను ఎంచుకోండి!"
  },
  kn: {
    appTitle: "ಮ್ಯಾಥ್ ಸಫಾರಿ",
    appSubtitle: "ಅನ್ವೇಷಣೆಯಲ್ಲಿ ಪಾಲ್ಗೊಳ್ಳಿ!",
    learnBtn: "ರಹಸ್ಯಗಳನ್ನು ಕಲಿ",
    startBtn: "ಸಾಹಸ ಪ್ರಾರಂಭಿಸು",
    fieldGuide: "ಮಾರ್ಗದರ್ಶಿ",
    chooseLevel: "ಹಂತ ಆರಿಸಿ",
    back: "ಹಿಂದಕ್ಕೆ",
    next: "ಮುಂದೆ",
    finish: "ಮುಗಿಸು",
    skip: "ಬಿಟ್ಟುಬಿಡು",
    go: "ಹೋಗು",
    del: "ಅಳಿಸು",
    oops: "ಅಯ್ಯೋ! ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    awesome: "ಅದ್ಭುತ!",
    nextChallenge: "ಮುಂದಿನ ಸವಾಲು",
    nextPart: "ಮುಂದಿನ ಭಾಗ",
    gotIt: "ಅರ್ಥವಾಯಿತು, ಮುಂದಿನ ಭಾಗ",
    finishStory: "ಕಥೆ ಮುಗಿಸು",
    guideSays: "ಮಾರ್ಗದರ್ಶಿ ಹೇಳುತ್ತಾರೆ:",
    easyAdd: "ಸುಲಭ ಸಂಕಲನ!",
    findHidden: "ಕೀಪ್ಯಾಡ್ ನೋಡಲು ಅಡಗಿರುವ ಸಂಖ್ಯೆಗಳನ್ನು ಹುಡುಕಿ!",
    breakNum: "ಬಿಡಿಸಿ",
    perfect: "ಅತ್ಯುತ್ತಮ!",
    findTen: "ಹತ್ತನ್ನು ಹುಡುಕಿ",
    letsLearn: "ಕಲಿಯೋಣ ಬನ್ನಿ!",
    correctIs: "ಸರಿಯಾದ ಉತ್ತರ",
    writingStory: "ಹೊಸ ಕಥೆ ಬರೆಯುತ್ತಿದ್ದೇನೆ...",
    congrats: "ಅಭಿನಂದನೆಗಳು!",
    points: "ನಿಮ್ಮ ಅಂಕಗಳು",
    l1_name: "ಪುಟ್ಟ ಹೆಜ್ಜೆಗಳು", l1_desc: "ಬಿಡಿಗಳ ಸಂಕಲನ (1-9)",
    l2_name: "ಹತ್ತುಗಳ ಗುಂಪು", l2_desc: "ಹತ್ತುಗಳ ಸಂಕಲನ (10, 20...)",
    l3_name: "ಸಂಖ್ಯೆ ಬಿಡಿಸುವವ", l3_desc: "ಬಿಡಿಸಿ ಮತ್ತು ಕೂಡಿಸಿ",
    l4_name: "ಸಣ್ಣ ವ್ಯವಕಲನ", l4_desc: "ಬಿಡಿಗಳ ವ್ಯವಕಲನ",
    l5_name: "ದೊಡ್ಡ ವ್ಯವಕಲನ", l5_desc: "ಹತ್ತುಗಳ ವ್ಯವಕಲನ",
    l6_name: "ಜಂಗಲ್ ಮಾಸ್ಟರ್", l6_desc: "ಮಿಶ್ರ ಸವಾಲು",
    l7_name: "ಕಥಾ ಸಫಾರಿ", l7_desc: "ಓದಿ, ನೆನಪಿಡಿ ಮತ್ತು ಪರಿಹರಿಸಿ!",
    step: "ಹೆಜ್ಜೆ",
    of: "ರಲ್ಲಿ",
    foundation: "ಬುನಾದಿ",
    smart: "ಚತುರ",
    breakTitle: "ಬಿಡಿಸಿ ನೋಡಿ",
    breakDesc: "ಸಂಖ್ಯೆಗಳನ್ನು ಹತ್ತು ಮತ್ತು ಬಿಡಿಗಳಾಗಿ ವಿಂಗಡಿಸಿ!",
    friendlyTitle: "ಸ್ನೇಹಿ ಸಂಖ್ಯೆಗಳು",
    friendlyDesc: "ಕಷ್ಟದ ಸಂಖ್ಯೆಗಳನ್ನು ಸೊನ್ನೆಯಿಂದ ಕೊನೆಗೊಳ್ಳುವ ಸುಲಭ ಸಂಖ್ಯೆಗಳನ್ನಾಗಿ ಮಾಡಿ.",
    selectLang: "ಭಾಷೆ ಆರಿಸಿ",
    hiGuide: "ನಮಸ್ಕಾರ! ನಾನು ಲಿಯೋ. ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ!"
  }
};

export const LEARN_CONTENT: Record<string, any[]> = {
  en: [
    {
      id: 'start-big', title: 'Start Big', steps: [
        { text: "Most kids try to add 3 + 12 by starting at 3 and counting up 12 times. That is slow!", visual: "slow" },
        { text: "The Trick: Always put the BIGGER number in your head first.", visual: "highlight" },
        { text: "Say '12' out loud, then count up '13, 14, 15'. Much faster!", visual: "fast" }
      ]
    },
    {
      id: 'plus-nine', title: 'Plus 9 Magic', steps: [
        { text: "Adding 9 is hard. But adding 10 is easy!", visual: "compare" },
        { text: "To add 9, just add 10 and jump back 1.", visual: "jump" },
        { text: "24 + 9? Think: 24 + 10 = 34. Minus 1 = 33!", visual: "solve" }
      ]
    },
    {
      id: 'doubles', title: 'Doubles + 1', steps: [
        { text: "If you know 6 + 6, you know 6 + 7!", visual: "doubles" },
        { text: "7 is just 6 + 1. They are neighbors.", visual: "neighbors" },
        { text: "So 6 + 7 is the same as (6 + 6) + 1. That's 12 + 1 = 13!", visual: "solve" }
      ]
    },
    {
      id: 'nine-ten', title: '9 & 10 Rule', steps: [
        { text: "Subtracting from 100 or 1000? Use the 'All from 9 and last from 10' rule.", visual: "intro" },
        { text: "100 - 36. Subtract the first digit (3) from 9.", visual: "step1" },
        { text: "Subtract the last digit (6) from 10. Answer is 64!", visual: "step2" }
      ]
    },
    {
      id: 'reverse', title: 'Reverse Add', steps: [
        { text: "Subtraction is hard. Addition is easy. Use addition to solve subtraction!", visual: "intro" },
        { text: "13 - 9 = ? Instead, think: 9 + ? = 13", visual: "bridge" },
        { text: "9... 10, 11, 12, 13. We needed 4 steps. The answer is 4!", visual: "solve" }
      ]
    },
    {
      id: 'same-change', title: 'Same Change', steps: [
        { text: "15 - 8 looks messy. Let's make the numbers friendly.", visual: "messy" },
        { text: "Add 2 to BOTH numbers. 8 becomes 10. 15 becomes 17.", visual: "shift" },
        { text: "17 - 10 = 7. The answer stays the same!", visual: "solve" }
      ]
    },
    {
      id: 'ten-jump', title: 'Ten Jump', steps: [
        { text: "Adding big numbers like 25 + 26 is hard. Don't do it all at once!", visual: "intro" },
        { text: "Break the second number into 10s. 26 becomes 10, 10, and 6.", visual: "split" },
        { text: "Jump by 10s! 25... 35... 45... plus 6 is 51. Easy peasy!", visual: "climb" }
      ]
    },
    {
      id: 'number-bonds', title: 'Make 10', steps: [
        { text: "Use your fingers to map numbers that make 10.", visual: "hands" },
        { text: "Fold down 3 fingers. You see 7 left standing.", visual: "fold" },
        { text: "3 + 7 = 10. These pairs are best friends.", visual: "friends" }
      ]
    },
    {
      id: 'break', title: 'Break Apart', steps: [
        { text: "23 + 45. Don't do it all at once.", visual: "split" },
        { text: "Smash them! Tens with Tens. Ones with Ones.", visual: "group" },
        { text: "20+40=60. 3+5=8. Answer: 68!", visual: "solve" }
      ]
    }
  ],
  gu: [
    {
      id: 'start-big', title: 'મોટી શરૂઆત', steps: [
        { text: "મોટાભાગના બાળકો 3 + 12 કરવા માટે 3 થી શરૂ કરીને 12 ગણે છે. આ ધીમું છે!", visual: "slow" },
        { text: "યુક્તિ: હંમેશા મોટી સંખ્યાને તમારા મગજમાં પહેલા રાખો.", visual: "highlight" },
        { text: "મોટેથી '12' બોલો, પછી '13, 14, 15' ગણો. ઘણું ઝડપી!", visual: "fast" }
      ]
    },
    {
      id: 'plus-nine', title: 'નવનો જાદુ', steps: [
        { text: "9 ઉમેરવા અઘરા છે. પણ 10 ઉમેરવા સરળ છે!", visual: "compare" },
        { text: "9 ઉમેરવા માટે, 10 ઉમેરો અને 1 પાછળ જાઓ.", visual: "jump" },
        { text: "24 + 9? વિચારો: 24 + 10 = 34. ઓછા 1 = 33!", visual: "solve" }
      ]
    },
    {
      id: 'doubles', title: 'ડબલ્સ + 1', steps: [
        { text: "જો તમને 6 + 6 આવડે, તો 6 + 7 પણ આવડે!", visual: "doubles" },
        { text: "7 એ માત્ર 6 + 1 છે. તેઓ પડોશીઓ છે.", visual: "neighbors" },
        { text: "તેથી 6 + 7 એ (6 + 6) + 1 જેવું છે. એટલે કે 12 + 1 = 13!", visual: "solve" }
      ]
    },
    {
      id: 'nine-ten', title: '9 અને 10 નો નિયમ', steps: [
        { text: "100 કે 1000 માંથી બાદબાકી? 'બધા 9 માંથી અને છેલ્લો 10 માંથી' નિયમ વાપરો.", visual: "intro" },
        { text: "100 - 36. પહેલા અંક (3) ને 9 માંથી બાદ કરો.", visual: "step1" },
        { text: "છેલ્લા અંક (6) ને 10 માંથી બાદ કરો. જવાબ 64 છે!", visual: "step2" }
      ]
    },
    {
      id: 'reverse', title: 'ઊંધો સરવાળો', steps: [
        { text: "બાદબાકી અઘરી છે. સરવાળો સરળ છે. બાદબાકી ઉકેલવા સરવાળાનો ઉપયોગ કરો!", visual: "intro" },
        { text: "13 - 9 = ? તેના બદલે વિચારો: 9 + ? = 13", visual: "bridge" },
        { text: "9... 10, 11, 12, 13. આપણને 4 પગલાં લાગ્યા. જવાબ 4 છે!", visual: "solve" }
      ]
    },
    {
      id: 'same-change', title: 'સમાન ફેરફાર', steps: [
        { text: "15 - 8 અઘરું લાગે છે. ચાલો નંબરોને મિત્ર બનાવીએ.", visual: "messy" },
        { text: "બંને નંબરમાં 2 ઉમેરો. 8 બને છે 10. 15 બને છે 17.", visual: "shift" },
        { text: "17 - 10 = 7. જવાબ તે જ રહે છે!", visual: "solve" }
      ]
    },
    {
      id: 'ten-jump', title: 'દસનો કૂદકો', steps: [
        { text: "25 + 26 જેવી મોટી સંખ્યાઓ ઉમેરવી અઘરી છે. એકસાથે ન કરો!", visual: "intro" },
        { text: "બીજી સંખ્યાને 10 માં તોડો. 26 બને છે 10, 10, અને 6.", visual: "split" },
        { text: "10 ના કૂદકા મારો! 25... 35... 45... વત્તા 6 એટલે 51. એકદમ સરળ!", visual: "climb" }
      ]
    },
    {
      id: 'number-bonds', title: '10 બનાવો', steps: [
        { text: "10 બનાવતા નંબરો જોવા તમારી આંગળીઓનો ઉપયોગ કરો.", visual: "hands" },
        { text: "3 આંગળીઓ વાળો. તમને 7 ઉભી દેખાશે.", visual: "fold" },
        { text: "3 + 7 = 10. આ જોડીઓ પાક્કા મિત્રો છે.", visual: "friends" }
      ]
    },
    {
      id: 'break', title: 'છૂટું પાડો', steps: [
        { text: "23 + 45. બધું એકસાથે ન કરો.", visual: "split" },
        { text: "તેમને તોડો! દસ સાથે દસ. એકમ સાથે એકમ.", visual: "group" },
        { text: "20+40=60. 3+5=8. જવાબ: 68!", visual: "solve" }
      ]
    }
  ]
};